### ISSUE TITLE
material testing results

### ISSUE THREAD

**Issue by alexgubanow** [GliaX/tourniquet#26]
hi, we are testing some materials for stretching against china made tourniquet, also will compare it with CAT ones.
As for now we can say that  stretching happens at initial loading, but not happen after all set.
Presumably this discussion can lead to recommendations for picking materials.
I was able to turn china made tourniquet for 720  degrees max, while for home made to get same force load i had to turn it for 1260. 
As for next step to test, I will gather straps with smaller "step", same as on china example. Seems like as smaller step of strap, as tighter it is - means should give less stretch.
For the slicing/printing details I will create separate issue, have some notes also.

![image](https://user-images.githubusercontent.com/12294794/170871097-46c0320d-00b4-436d-815d-fcc691f5a6c5.png)

**Comment by apopanda** [comment]
The windlass isn't a helicopter. More turns doesn't mean better. The tourniquet is supposed to stop bloodflow after ~3, maybe 4 half turns, but have a significant overhead so it doesn't break. It expanding on initial load means the material isn't suitable. Try a heavy nylon webbing, it should stay put, even with multiple uses. Also that thing you're wrapping them on doesn't seem suitable for checking tourniquets, the backing plate should bend over the leg for instance, while on your photo it's rigid straight.

**Comment by alexgubanow** [comment]
Exactly, too many turns suggest that material stretched, a lot.
We just got few samples of 25mm straps, will report about results later.
The same red tube used to test the original tourniquet, while it was possible to turn only for 720 degrees. Based on that, my assumption is whatever sample will be tested, should not go above 720 degrees.
I’m looking for some piece of wood or something, to remove questions here.

**Comment by apopanda** [comment]
Well, a piece of wood / hard stuff isn't ideal either. Don't base your tests on the chineese ones, only original CAT should be the norm, and even those fail 20% of the time according to some data we've found. 
The ukrainian test centers test their tourniquet on live patients, and check for pulse with doppler USG. They do a bunch of other stuff too, but @tareko has mentioned that their testing seems counterproductive (i.e. why do you need a walk test for someone who needs a tourniquet on their leg). For destructive testing we're still looking for solutions. The 720 degree as a baseline isn't a good one though, I personally had one that went up to 8 half rotations (when people use "turns" in regard to tourniquets here, they usually mean one hand movement, so 180 degrees). You needed to use a metal rod for it, and it lost all plastic, but you could turn it that way. I think I saw 6 halfturns as the recommended maximum?

The issue here is that we don't have a reliable testing framework for them yet. Number of turns isn't one that we should compare, since it's too dependant on other factors. You can't turn too much, or you heighten the risk of amputation and other bad stuff happening. You can't have a tourniquet that works up to 4 halfturns, or you risk an unexperienced user breaking them when they need them most, when they give them a "one more for good measure".

**Comment by alexgubanow** [comment]
let me make my point clear, this issue is aimed to find best suite material, only.
Testing of final product will be conducted, after we find suitable materials. 
The test was carried at home with whatever tools was available. Today we hope to measure collected strap samples with tensile machine. We will compare properties of materials used in CAT against what available to us here.

About framework for final product testing, We will send 5-10pcs to Kharkiv medics to test, not to the army guys. The approach with ultrasonic is good one, will see what else option we have.
At the very moment, paramedics simply washing used tourniquets and use it again. we simply can't standstill.

**Comment by apopanda** [comment]
@tareko will be going back through Cracow in the beginning of June and he'll meet with me. He'll be grabbing some materials and taking them to Canada, so Glia can check them out and give their stamp of approval. Glia doesn't have a lab for testing those though, so it'd be mostly comparing to what they use in Canada to make the original ones. You can contact me at adam.popanda@gmail.com, send me the link to ones you'd like to test which I can get in Poland. I'll get them and throw them in for Tarek's goodie bag. The sooner I'd get that, the better, since I don't exactly know when Tarek will be going through here and whether a courier could get here in time. Mostly talking about inner straps. 

RE: "we simply can't standstill" - we can, and we have to. We can't rush into tourniquet production. There's already too many projects that do that and send tourniquets that break. There's huge stigma surrounding 3dp tourniquets in Ukraine currently because of "innovative" projects. I think Tarek has a blogpost about this specific issue. Glia's design is tested in Gaza, but it still has room for improvement. We've seen people replicate the design and make huge mistakes. Even Glia made mistakes in some of the units sent to Ukraine. 

I love your enthusiasm. It's great that there are people out there doing stuff, making tourniquets. The issue is that it's a complex piece of medical equipment which kills people when it fails. We need to be 110% sure it won't fail before sending them out for testing. Otherwise they'll reject every single one, including ones that'd work after the mistakes are fixed.

**Comment by tareko** [comment]
Hey guys! Well done on getting this far, @alexgubanow ! And thank you so much @apopanda for your great comments. I echo many of @apopanda's observations about the importance of careful testing, and I feel like @alexgubanow you and your team are working hard on this.

In terms of the material, from the photos it does seem that the weave is too 'loose'. We are also trying to generate an appropriate specification for the internal belt, so I share with you the sentiment that it is not well-enough characterized in our documents and indeed in the industry.

One simple rule is that the internal strap should consist of material made for rock climbing like [this one](https://www.mec.ca/en/product/5020-829/1%22%2825mm%29-Nylon-Tubular-Climbing-Webbing) (I haven't looked, so don't take this as an unqualified endorsement). That seems to be the one distinction between the high-quality and low-quality straps we've found.

We're working now on a proper specification, but this has proved difficult as manufacturers don't often report it that way. However, stick with the rule of 'climbing strap', and you should be OK.

**Comment by alexgubanow** [comment]
Yeap, we can see same relation in our tension tests today with tensile machine.
Just so you all know my background, I'm 3rd year PhD student of VGTU, Biomechanics. My topic is numerical models of heart mitral valve. But I do many "mechanics" as well. Never the less, the professor from "properties of materials" pointed for - we better do twisting and load over time tests, as it will cover all stress tourniquet is experiencing.
The length for stretch test is about the same is in action on leg and is ~60cm.
I will draw some nice charts from data in matlab later, very busy packing parcel to Ukraine for tomorrow.
The best from today - gave about 240kg load while 70mm stretch.
![photo_2022-05-31_00-47-58](https://user-images.githubusercontent.com/12294794/171062171-2c5f59d4-704a-4695-8b5d-eec02af1f4cc.jpg)
![photo_2022-05-31_00-47-57](https://user-images.githubusercontent.com/12294794/171062175-10bbd3e5-df7f-42ca-9fba-d53f9478b22a.jpg)

short video of setup
https://user-images.githubusercontent.com/12294794/171061627-c07d9563-6df1-4b04-a444-7f6cfc303957.MOV

**Comment by jenwilsonglia** [comment]
@alexgubanow Wondering if you have the data from your tests. We've conducted tensile strength tests on our inner strap webbing materials. You can find these at https://github.com/GliaX/tourniquet/blob/master/assembly_instructions/quality_control/inner%20belt%20tensile%20strength%20notes.md

**Comment by alexgubanow** [comment]
hi, i have not saved the tests. from what i recall, the most suitable material was a safety belt from car.
