### ISSUE TITLE
[FEATURE REQUEST] Add PETG print settings to readme

### ISSUE THREAD

**Issue by darigovresearch** [GliaX/tourniquet#54]
Design intent says PETG is also acceptable, thought it would be able to add the print settings to the readme with the settings you have been using 

Design intent https://github.com/GliaX/tourniquet/blob/master/assembly_instructions/quality_control/design%20intent.md

Print settings https://github.com/GliaX/tourniquet#print-settings

**Comment by jenwilsonglia** [comment]
For Design Intent, we could change first paragraph to "ABS and PETG are acceptable materials to use to print the plastic parts of the tourniquet. PLA is not an acceptable material because it does not withstand exposure to UV light or exposure to the elements well." 

For Print Settings, let's add PETG and distinguish the different bed temps (85 C for PETG). Layer Height and Infill are the same for ABS and PETG.

Let me know if you want to create the pull request, or if you'd like me to do it.  Thanks

**Comment by darigovresearch** [comment]
Thanks @jenwilsonglia for the feedback, pull request https://github.com/GliaX/tourniquet/pull/63 should resolve this issue if merged

**Comment by jenwilsonglia** [comment]
Pull request #63 has been merged. Thanks @darigovresearch !
